---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-socket-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: node-socket-server
  template:
    metadata:
      labels:
        app: node-socket-server
    spec:
      containers:
      - name: node-socket-server
        #image: node-socket-server:1.0
        image: bflk8spoc.azurecr.io/node-socket-server:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8093
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1000m 
      restartPolicy: Always
      imagePullSecrets:
      - name: apisecret
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-socket-server
  namespace: default 
spec:
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: node-socket-server
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
status:
  observedGeneration: 5
  currentReplicas: 5
  desiredReplicas: 5
---
apiVersion: v1
kind: Service
metadata:
  name: node-socket-server
  labels:
    app: node-socket-server
spec:
  type: LoadBalancer
  #loadBalancerIP: 52.172.187.91
  selector:
    app: node-socket-server
  ports:
  - protocol: TCP
    port: 8093
    name: http

---